apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurestorage-elastic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurestorage-elastic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurestorage-elastic
  template:
    metadata:
      labels:
        app: azurestorage-elastic
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: elasticcontainer
        image: elasticsearch:7.17.7
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: mydir
      volumes:
      - name: mydir
        persistentVolumeClaim:
          claimName: azurestorage-elastic-pvc