apiVersion: apps/v1
kind: Deployment
metadata:
  name: neticapiswid-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: neticapiswid
  template:
    metadata:
      labels:
        app: neticapiswid
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: sa-testaccount
      containers:
        - name: neticapiswid-container
          image: acrintitaksmlc2.azurecr.io/neticapis:1.1
          