apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksapis-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aksapis
  template:
    metadata:
      labels:
        app: aksapis
    spec:
      containers:
        - name: aksapis-container
          image: acrintitaksmlc.azurecr.io/aksapis:1.1
          