apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrtest-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: acrtest
  template:
    metadata:
      labels:
        app: acrtest
    spec:
      containers:
        - name: acrtest-container
          image: acrintitaksmlc.azurecr.io/aksapis:1.2
          